name: "Tests e2e"
on:
  pull_request:

jobs:
  tests_on_chrome_linux:
    name: "Chrome Stable (Linux)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i -g npm@8
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:ci
        env:
          PWTEST_CHANNEL: chrome
